packages:
  - api
  - worker
  - search-bot

ignoredBuiltDependencies:
  - '@nestjs/core'
  - bufferutil
  - es5-ext
  - msgpackr-extract
  - utf-8-validate

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - prisma
